### ISSUE TITLE
[FP] nitrokey.com

### ISSUE THREAD

**Issue by devipasigner** [Dogino/Discord-Phishing-URLs#15]
Domain was flagged because of the keyword 'nitro' I'm assuming. 
Nitrokey is an open-source USB key used to enable the secure encryption and signing of data. The secret keys are always stored inside the Nitrokey which protects against malware and attackers. A user-chosen PIN and a tamper-proof smart card protect the Nitrokey in case of loss and theft.

**Comment by Dogino** [comment]
Thanks for reporting! It was indeed a false positive caused by the regex.
Domain removed in [947e2d5](https://github.com/Dogino/Discord-Phishing-URLs/commit/947e2d5cee9e2a89a037906b1bf70e46b61c1f90)
