### ISSUE TITLE
invalid domains

### ISSUE THREAD

**Issue by Ash3781** [Dogino/Discord-Phishing-URLs#22]
hey, i noticed while trailing an update that there are a total of 8 invalid domains in your domain list, however i can only see 5 of them through my update log because of how pihole displays them, here are the 5 i can see:
```
[✓] Parsed 28318 exact domains and 0 ABP-style domains (ignored 8 non-domain entries)
Sample of non-domain entries:
- "discörd.com"
- "disçordapp.com"
- "getlⅰbra.tech"
- "gg.gg/win-nitro"
- "org-rоblох.com"
```
i don't quite get what's wrong with the last displayed domain, my guess is that there are look-alike characters from other character sets

**Comment by Dogino** [comment]
Hello! Thank you for letting me know. Fixed in [8196ec5](https://github.com/Dogino/Discord-Phishing-URLs/commit/8196ec581db8a54462541de5f407e435cd15c6f9)
