### ISSUE TITLE
Do you have the full urls?

### ISSUE THREAD

**Issue by neevaiti** [Dogino/Discord-Phishing-URLs#27]
I'm working on a phishing url detection AI model to expand my dataset. 
I'd like to know if you have full urls like: http://example.com/ | https://example.com...

Thank you!

**Comment by T145** [comment]
@neevaiti If you'd like lists that have full URLs, check out entries in my [list manifest](https://raw.githubusercontent.com/T145/black-mirror/master/data/v2/manifest.json) that use a `ABUSE_CH_URLHAUS_*` filter.

**Comment by neevaiti** [comment]
Nice, thank you
