### ISSUE TITLE
False positive: discordservers.com

### ISSUE THREAD

**Issue by sefinek** [Dogino/Discord-Phishing-URLs#28]
Found 2 lists exactly matching 'discordservers.com':

  - https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/Dogino/Discord-Phishing-URLs-phishing.fork.txt
    block list
    added:         2024-09-02 01:07:19
    last modified: 2024-09-02 01:07:19
    last updated:  2024-09-08 03:57:47 (33,502 domains)
    enabled, used in 1 group
    no comment
    matching entries:
    - discordservers.com

  - https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/Dogino/Discord-Phishing-URLs-scam.fork.txt
    block list
    added:         2024-09-02 01:07:19
    last modified: 2024-09-02 01:07:19
    last updated:  2024-09-08 03:58:14 (33,493 domains)
    enabled, used in 1 group
    no comment
    matching entries:
    - discordservers.com

**Comment by Dogino** [comment]
Removed in [b6e0432](https://github.com/Dogino/Discord-Phishing-URLs/commit/b6e0432b10d95796a2aed546612f786841aefb7f)
