### ISSUE TITLE
Analyzed 10632 domains, 1 domains invalid!

### ISSUE THREAD

**Issue by ghost** [Dogino/Discord-Phishing-URLs#4]
Please excuse my brevity, but I get the following warning when updating Gravity on Pi-Hole with your Pi-Hole list:
```
  [i] Target: https://raw.githubusercontent.com/Dogino/Discord-Phishing-URLs/main/pihole-phishing-adlist.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 10632 domains, 1 domains invalid!
      Sample of invalid domains:
      - clk.rtpdn*.com
```
I don't think it likes the wildcard character.

Docker Tag [2022.02.1](https://github.com/pi-hole/docker-pi-hole/releases/2022.02.1) Pi-hole [v5.9](https://github.com/pi-hole/pi-hole/releases/v5.9) FTL [v5.14](https://github.com/pi-hole/FTL/releases/v5.14) Web Interface [v5.11](https://github.com/pi-hole/AdminLTE/releases/v5.11)

**Comment by Dogino** [comment]
No problem! Thank you for reporting it, it was indeed an invalid domain, changed with the latest domain update
